### ISSUE TITLE
Release 0.0.28 contains wrong rust MSRV in README.md

### ISSUE THREAD

**Issue by ecordonnier-sc** [uutils/coreutils#7293]
Hello,
feel free to close and treat it as information only. I noticed this while working on the integration of uutils-coreutils 0.0.28 into Yocto and thought it could be relevant. Maybe some CI job needs to be changed to build with selinux enabled?

Commit 10d3e98eda which is between release 0.0.27 and release 0.0.28 updated selinux-sys to a version which requires Rust 1.77, because it uses "offset_of".

0.0.28 fails to compile with 1.70 with selinux enabled:

```
ecordonnier@lj8k2dq3:~/dev/coreutils$ rustup install 1.70
ecordonnier@lj8k2dq3:~/dev/coreutils$ cargo +1.70 build --features selinux
...
error[E0433]: failed to resolve: could not find `offset_of` in `mem`
    --> /home/ecordonnier/dev/coreutils/target/debug/build/selinux-sys-1def5c504f36bce5/out/selinux-sys.rs:1384:54
     |
1384 |     ["Offset of field: dir_xattr::next"][::std::mem::offset_of!(dir_xattr, next) - 24usize];
     |                                                      ^^^^^^^^^ could not find `offset_of` in `mem`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `selinux-sys` (lib) due to 43 previous errors

```
0.0.28 actually requires rust 1.77 when selinux is enabled:
```
$ rustup install 1.77
$ cargo clean
$ cargo +1.77 build --features selinux
warning: /home/ecordonnier/dev/coreutils/src/uu/seq/Cargo.toml: unused manifest key: lints.rust.unexpected_cfgs.check-cfg
    Finished dev [unoptimized + debuginfo] target(s) in 1.31s
```

**Comment by RenjiSann** [comment]
Well, I am not sure of the benefit of pushing a 0.0.28.1 version just to fix a typo in the 0.0.28 release which is now superseded by 0.0.29.

I would qualify this as wontfix.

**Comment by Ecordonnier** [comment]
Yes, feel free to close as wontfix. I just wanted to let you know in case a CI job verifying the MSRV needs to be fixed.

**Comment by RenjiSann** [comment]
Will do this, thank you for reporting it nonetheless !
