### PR TITLE
`uucore`: Fix #4298: Fails to build on s390x (and riscv64)

### LINKED ISSUE #4298: Fails to build on s390x with `error[E0308]: mismatched types`
@Joining7943 seems that it is caused by c94a039358?

```

   Compiling uucore v0.0.17 (/<<PKGBUILDDIR>>/src/uucore)
error[E0308]: mismatched types
   --> src/uucore/src/lib/features/fsext.rs:624:16
    |
616 |     fn block_size(&self) -> i64 {
    |                             --- expected `i64` because of return type
...
624 |         return self.f_bsize;
    |                ^^^^^^^^^^^^ expected `i64`, found `u32`
    |
help: you can convert a `u32` to an `i64`
    |
624 |         return self.f_bsize.into();
    |                            +++++++

error[E0308]: mismatched types
   --> src/uucore/src/lib/features/fsext.rs:686:16
    |
678 |     fn fs_type(&self) -> i64 {
    |                          --- expected `i64` because of return type
...
686 |         return self.f_type;
    |                ^^^^^^^^^^^ expected `i64`, found `u32`
    |
help: you can convert a `u32` to an `i64`
    |
686 |         return self.f_type.into();
    |                           +++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `uucore` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

Full log:
https://buildd.debian.org/status/fetch.php?pkg=rust-coreutils&arch=s390x&ver=0.0.17-1&stamp=1674426143&raw=0

### PR DESCRIPTION
**Pull request by Joining7943**
I ran the builds locally with `cross` without the errors occurring in the failed builds here https://buildd.debian.org/status/logs.php?pkg=rust-coreutils&ver=0.0.17-1

The commands I used were:
```
$ cross build --target s390x-unknown-linux-gnu --features unix
$ cross build --target riscv64gc-unknown-linux-gnu --features unix
```

Closes #4298

### CODE REVIEW

**Comment by sylvestre** [comment]
Fixed, thanks :)
https://buildd.debian.org/status/package.php?p=rust-coreutils
