### PR TITLE
Fix and enforce MSRV by building all features during CI

### LINKED ISSUE #6728: MSRV >= 1.77 when building with --all-features
Trying to compile with 1.70 (= our MSRV, according to the README) and all features fails, despite the MSRV CI succeeding:

```console
$ cargo +1.70.0 build --all-features
warning: /home/user/workspace/coreutils-rs/src/uu/seq/Cargo.toml: unused manifest key: lints
warning: /home/user/workspace/coreutils-rs/Cargo.toml: unused manifest key: lints
   Compiling selinux-sys v0.6.12
   Compiling fts-sys v0.2.11
error[E0433]: failed to resolve: could not find `offset_of` in `mem`
  --> /home/user/workspace/coreutils-rs/target/debug/build/fts-sys-35eedc7d1c3cabc2/out/fts-sys.rs:63:57
   |
63 |     ["Offset of field: _ftsent::fts_cycle"][::std::mem::offset_of!(_ftsent, fts_cycle) - 0usize];
   |                                                         ^^^^^^^^^ could not find `offset_of` in `mem`
<SNIP: many more such errors>
For more information about this error, try `rustc --explain E0433`.
error: could not compile `fts-sys` (lib) due to 20 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `selinux-sys` (lib) due to 43 previous errors
[$? = 101]
```

The cause seems to be:
- `chcon` uses `fts-sys=0.2.9`, which uses https://doc.rust-lang.org/std/mem/macro.offset_of.html which was introduced in Rust 1.77.0
- `chcon` is not built during CI, and no other feature/util uses this crate, which is why it slipped through the cracks.

Suggestion: Downgrade fts-sys and build all features during MSRV CI. What do you think?

### PR DESCRIPTION
**Pull request by BenWiederhake**
This PR:
- downgrades fts-sys and selinux-sys (erroneously upgraded in #6339) to achieve MSRV 1.70.0 again
- enforces MSRV by *actually* compiling all code during CI.

Note that the latter requires that we split the text step into two steps, because `cargo nextest --all-features` would also include features such as `test_unimplemented` and `expensive_tests`, which would always break.

Fixes #6728.

### CODE REVIEW

**Comment by BenWiederhake** [comment]
- Some of our code uses itertools' `chunk_by` feature, which is only introduced in 0.13.0
- Any fts-sys version that is old enough to work with rust 1.70.0 depends on itertools < 0.13.0, e.g. 0.12.1
- If we use both itertools 0.12.1 and 0.13.0 at the same time, then a lint complains about that.

I see only these options:
- Raise MSRV to >= 1.77 (ugh!)
- Permit using two different versions of itertools at the same time (ugh!)
- Claim that we still have an MSRV of 1.70 for "most" of the code, but it breaks with `--feature chcon` (ugh!)

All of these are terrible. @sylvestre How would you like to proceed?

**Comment by samueltardieu** [comment]
>     * Raise MSRV to >= 1.77 (ugh!)

What is really the problem with raising the MSRV to 1.77.0? Debian stable uses rust 1.65.0 by default, which is older than 1.70 anyway so people stuck with Debian stable have to use rustup and can probably use 1.77.0 (which is more than 6 months old). Debian testing uses 1.80.1, so this is ok.

Who are the "customers" of `coreutils` that can deal use 1.70.0 and cannot deal with 1.77.0? Is it worth holding back commodity packages such as `itertools` for them? Can't they work with an earlier version of `coreutils`? Will they want to use the current daily version anyway if they are not allowed to upgrade their compilers, why could they upgrade their coreutils?

**Comment by BenWiederhake** [comment]
Feel free to open a PR to do so, but I don't want to make a decision on this.

**Comment by samueltardieu** [comment]
@sylvestre?

**Comment by sylvestre** [comment]
@samueltardieu @BenWiederhake 
we aren't at a stage of the project that we have to worry at the LTS support. 
So, IMHO, we can be relaxed about upgrading the rust minimal version for now

**Comment by BenWiederhake** [comment]
Welp, that makes this entire PR obsolete.
