### ISSUE TITLE
tests/uucore: build failure

### ISSUE THREAD

**Issue by xtqqczze** [uutils/coreutils#11617]
```sh
cargo +stable build --workspace --tests
```

```log
error[E0425]: cannot find function `pipe` in module `pipes`
  --> src/uucore/src/lib/features/buf_copy.rs:73:54
   |
73 |         let (mut pipe_read, mut pipe_write) = pipes::pipe().unwrap();
   |                                                      ^^^^ not found in `pipes`
   |
note: found an item that was configured out
  --> src/uucore/src/lib/features/pipes.rs:22:8
   |
21 | #[cfg(any(target_os = "linux", target_os = "android"))]
   |          -------------------------------------------- the item is gated here
22 | pub fn pipe() -> std::io::Result<(File, File)> {
   |        ^^^^
help: consider importing one of these functions
   |
26 +     use std::io::pipe;
   |
26 +     use libc::pipe;
   |
26 +     use nix::unistd::pipe;
   |
26 +     use rustix::pipe::pipe;
   |
help: if you import `pipe`, refer to it directly
   |
73 -         let (mut pipe_read, mut pipe_write) = pipes::pipe().unwrap();
73 +         let (mut pipe_read, mut pipe_write) = pipe().unwrap();
   |

error[E0282]: type annotations needed
  --> src/uucore/src/lib/features/buf_copy.rs:76:13
   |
76 |             pipe_write.write_all(data).unwrap();
   |             ^^^^^^^^^^ cannot infer type
```

**Comment by xtqqczze** [comment]
@sylvestre @oech3 Broken by 04b15859eeef37ae12a9b3975932ef39f9e951b0

**Comment by oech3** [comment]
This is used only at Linux (at least for production).

**Comment by sylvestre** [comment]
ok
we should have a ci job to cover this case :)

**Comment by oech3** [comment]
CI is very difficult since it pulls many unsupported utils.
https://github.com/uutils/coreutils/issues/7396
https://github.com/uutils/coreutils/issues/7397

**Comment by xtqqczze** [comment]
> ok we should have a ci job to cover this case :)

The issue is we don't specify the `--workspace` option in clippy or otherwise.

**Comment by xtqqczze** [comment]
> CI is very difficult since it pulls many unsupported utils. [#7396](https://github.com/uutils/coreutils/issues/7396) [#7397](https://github.com/uutils/coreutils/issues/7397)

We don't need to run the test necessarily, just ensure there are no clippy warnings.

**Comment by oech3** [comment]
Is `cargo +stable check --workspace --tests` on macOS enough?

**Comment by xtqqczze** [comment]
That would have prevented this issue, but I expect we want to run clippy as well.

**Comment by xtqqczze** [comment]
The issue is not resolved, please reopen:

```log
$ cargo +stable clippy --workspace --tests --target aarch64-apple-darwin --quiet
error[E0425]: cannot find type `File` in this scope
  --> src/uucore/src/lib/features/pipes.rs:24:35
   |
24 | pub fn pipe() -> std::io::Result<(File, File)> {
   |                                   ^^^^ not found in this scope
   |
   = note: struct `crate::checksum::validate::tests::File` exists but is inaccessible
help: consider importing this struct
   |
 8 + use std::fs::File;
   |
...
```
