### ISSUE TITLE
Fails to build on s390x with `error[E0308]: mismatched types`

### ISSUE THREAD

**Issue by sylvestre** [uutils/coreutils#4298]
@Joining7943 seems that it is caused by c94a039358?

```

   Compiling uucore v0.0.17 (/<<PKGBUILDDIR>>/src/uucore)
error[E0308]: mismatched types
   --> src/uucore/src/lib/features/fsext.rs:624:16
    |
616 |     fn block_size(&self) -> i64 {
    |                             --- expected `i64` because of return type
...
624 |         return self.f_bsize;
    |                ^^^^^^^^^^^^ expected `i64`, found `u32`
    |
help: you can convert a `u32` to an `i64`
    |
624 |         return self.f_bsize.into();
    |                            +++++++

error[E0308]: mismatched types
   --> src/uucore/src/lib/features/fsext.rs:686:16
    |
678 |     fn fs_type(&self) -> i64 {
    |                          --- expected `i64` because of return type
...
686 |         return self.f_type;
    |                ^^^^^^^^^^^ expected `i64`, found `u32`
    |
help: you can convert a `u32` to an `i64`
    |
686 |         return self.f_type.into();
    |                           +++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `uucore` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

Full log:
https://buildd.debian.org/status/fetch.php?pkg=rust-coreutils&arch=s390x&ver=0.0.17-1&stamp=1674426143&raw=0

**Comment by Joining7943** [comment]
yeah it's definitely since #4238. the `risc64` build fails too https://buildd.debian.org/status/fetch.php?pkg=rust-coreutils&arch=riscv64&ver=0.0.17-1&stamp=1674429761&raw=0. I'll try to figure it out. Both `s390x` and `risc64gc` would be supported by `cross`. Should we add them to the ci?
