### PR TITLE
Fix build on NetBSD

### LINKED ISSUE #11175: 0.6.0 release broken on NetBSD
Hi,

`coreutils` v0.5.0 builds fine on NetBSD, while v0.6.0 fails to build `uucore` with:

```
error[E0609]: no field `st_atime_nsec` on type `FileStat`
   --> /usr/pkgsrc/wip/nushell/work/vendor/uucore-0.6.0/src/lib/features/safe_traversal.rs:482:23
    |
482 |             self.stat.st_atime_nsec
    |                       ^^^^^^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
482 -             self.stat.st_atime_nsec
482 +             self.stat.st_atimensec
    |

error[E0609]: no field `st_mtime_nsec` on type `FileStat`
   --> /usr/pkgsrc/wip/nushell/work/vendor/uucore-0.6.0/src/lib/features/safe_traversal.rs:504:23
    |
504 |             self.stat.st_mtime_nsec
    |                       ^^^^^^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
504 -             self.stat.st_mtime_nsec
504 +             self.stat.st_mtimensec
    |

error[E0609]: no field `st_ctime_nsec` on type `FileStat`
   --> /usr/pkgsrc/wip/nushell/work/vendor/uucore-0.6.0/src/lib/features/safe_traversal.rs:526:23
    |
526 |             self.stat.st_ctime_nsec
    |                       ^^^^^^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
526 -             self.stat.st_ctime_nsec
526 +             self.stat.st_ctimensec
    |
```

This was observed while building `nushell` v0.111.0 see, https://github.com/nushell/nushell/issues/17695#issuecomment-3984104778

The same happens building `coreutils` standalone with cargo.

The reason is rather obvious,
```
~> grep -r "st_atime_nsec" libc-0.2.178/src/unix/bsd/netbsdlike/netbsd
Exception: grep exited with 1
~> grep -r "st_mtime_nsec" libc-0.2.178/src/unix/bsd/netbsdlike/netbsd
Exception: grep exited with 1
~> grep -r "st_ctime_nsec" libc-0.2.178/src/unix/bsd/netbsdlike/netbsd
Exception: grep exited with 1
~> grep -r "st_atimensec" libc-0.2.178//src/unix/bsd/netbsdlike/netbsd
libc-0.2.178/src/unix/bsd/netbsdlike/netbsd/mod.rs:        pub st_atimensec: c_long,
~> grep -r "st_mtimensec" libc-0.2.178//src/unix/bsd/netbsdlike/netbsd
libc-0.2.178/src/unix/bsd/netbsdlike/netbsd/mod.rs:        pub st_mtimensec: c_long,
~> grep -r "st_ctimensec" libc-0.2.178//src/unix/bsd/netbsdlike/netbsd
libc-0.2.178/src/unix/bsd/netbsdlike/netbsd/mod.rs:        pub st_ctimensec: c_long,
```

And the same output is valid for the latest `libc`, v0.2.182.

Any reason for this regression and are you willing to fix it?

### PR DESCRIPTION
**Pull request by 0323pin**
Closes #11175

### CODE REVIEW

**Comment by oech3** [comment]
Please  `cargo fmt`

**Comment by 0323pin** [comment]
> Please `cargo fmt`

I did run `rustfmt` on the changed file. Do you want me to cover the whole repository?

**Comment by oech3** [comment]
You can manuall apply https://github.com/uutils/coreutils/actions/runs/22580473167/job/65410881118?pr=11176 as a workaround.

**Comment by 0323pin** [comment]
> You can manuall apply https://github.com/uutils/coreutils/actions/runs/22580473167/job/65410881118?pr=11176 as a workaround.

Lets see how it goes.

**Comment by oech3** [comment]
https://github.com/uutils/coreutils/actions/runs/22581923134/job/65416087843?pr=11176

File: src/uucore/src/lib/features/safe_traversal.rs
[the remark this answers is not in the document]
Comment (oech3) [reply src/uucore/src/lib/features/safe_traversal.rs]: Add missing words

**Comment by cakebaker** [comment]
Thanks!

**Comment by 0323pin** [comment]
> Thanks!

Thank you!
