### PR TITLE
cp: improve the selinux support

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by cakebaker** [comment]
The code currently fails due to the changes in https://github.com/uutils/coreutils/pull/7845:
```
error[E0277]: `?` couldn't convert the error to `Error`
    --> src/uu/cp/src/cp.rs:2461:86
     |
2251 | ) -> CopyResult<()> {
     |      -------------- expected `Error` because of this
...
2461 |         uucore::selinux::set_selinux_security_context(dest, options.context.as_ref())?;
     |         -----------------------------------------------------------------------------^ the trait `From<SeLinuxError>` is not implemented for `Error`
     |         |
     |         this can't be annotated with `?` because it has type `Result<_, SeLinuxError>`

```

File: tests/by-util/test_cp.rs [hunk 1]
```diff
@@ -6248,3 +6248,421 @@ fn test_cp_update_none_interactive_prompt_no() {
...
+            .arg(TEST_HELLO_WORLD_DEST)
+            .arg("--preserve=all")
+            .succeeds();
+        assert!(at.file_exists(TEST_HELLO_WORLD_DEST));
+        let selinux_perm_dest = get_getfattr_output(&at.plus_as_string(TEST_HELLO_WORLD_DEST));
+        assert!(
+            selinux_perm_dest.contains("unconfined_u"),
+            "Expected '{}' not found in getfattr output:\n{}",
+            "foo",
+            selinux_perm_dest
```
Comment (cakebaker) [inline tests/by-util/test_cp.rs:6347]:
```suggestion
            "Expected 'foo' not found in getfattr output:\n{selinux_perm_dest}"
```

File: tests/by-util/test_cp.rs [hunk 2]
```diff
@@ -6248,3 +6248,421 @@ fn test_cp_update_none_interactive_prompt_no() {
...
+#[cfg(feature = "feat_selinux")]
+fn test_cp_preserve_selinux_admin_context() {
+    let ts = TestScenario::new(util_name!());
+    let at = &ts.fixtures;
+
+    at.touch(TEST_HELLO_WORLD_SOURCE);
+
+    // Get the default SELinux context for the destination file path
+    // on Debian/Ubuntu, this program is provided by the selinux-utils package
+    // on Fedora/RHEL, this program is provided by the libselinux-devel package
```
Comment (cakebaker) [inline tests/by-util/test_cp.rs:6377]:
```suggestion
    // Get the default SELinux context for the destination file path.
    // On Debian/Ubuntu, this program is provided by the selinux-utils package.
    // On Fedora/RHEL, this program is provided by the libselinux-devel package.
```

File: tests/by-util/test_cp.rs [hunk 3]
```diff
@@ -6248,3 +6248,421 @@ fn test_cp_update_none_interactive_prompt_no() {
...
+#[cfg(feature = "feat_selinux")]
+fn test_cp_selinux_context_priority() {
+    // This test verifies that the priority order is respected:
+    // -Z > --context > --preserve=context
+
+    let ts = TestScenario::new(util_name!());
+    let at = &ts.fixtures;
+
+    // Create two different files
+    at.write(TEST_HELLO_WORLD_SOURCE, "source content");
```
Comment (cakebaker) [inline tests/by-util/test_cp.rs:6436]: Either the comment is incorrect or the code. There is only one call of `at.write()`.

File: src/uu/cp/src/cp.rs [hunk 4]
```diff
@@ -1613,10 +1640,12 @@ fn copy_extended_attrs(source: &Path, dest: &Path) -> CopyResult<()> {
 }
 
 /// Copy the specified attributes from one path to another.
+#[allow(unused_variables)]
 pub(crate) fn copy_attributes(
     source: &Path,
     dest: &Path,
     attributes: &Attributes,
+    options: &Options,
```
Comment (cakebaker) [inline src/uu/cp/src/cp.rs:1648]: What's the reason for this parameter?

Comment (sylvestre) [reply src/uu/cp/src/cp.rs:1648]: carryover from the previous work, I might be able to remove it
