### ISSUE TITLE
Compilation failure using 'make install' on Mac 

### ISSUE THREAD

**Issue by kevinburke** [uutils/coreutils#7695]
I'm trying to compile coreutils on my Mac. I have tried both stable and nightly, installed from rustup, and I am installing by invoking `make install` from the top level of the repo. 

Here is what I see for build output, when I try to compile th

```txt
make install PREFIX=/Users/kburke/local/coreutils
cargo build  --features "arch base32 base64 basename basenc cat chcon chgrp chmod chown chroot cksum comm cp csplit cut date dd df dir dircolors dirname du echo env expand expr factor false fmt fold groups hashsum head hostid hostname id install join kill link ln logname ls mkdir mkfifo mknod mktemp more mv nice nl nohup nproc numfmt od paste pathchk pinky pr printenv printf ptx pwd readlink realpath rm rmdir runcon seq shred shuf sleep sort split stat stdbuf sum sync tac tail tee test timeout touch tr true truncate tsort tty uname unexpand uniq unlink uptime users vdir wc who whoami yes " --release --no-default-features
  Downloaded half v2.6.0
  Downloaded 1 crate (59.5 KB) in 0.93s
   Compiling libc v0.2.171
   Compiling proc-macro2 v1.0.94
   Compiling unicode-ident v1.0.18
   Compiling cfg-if v1.0.0
   Compiling memchr v2.7.4
   Compiling shlex v1.3.0
   Compiling regex-syntax v0.8.5
   Compiling autocfg v1.4.0
   Compiling bitflags v2.9.0
   Compiling cc v1.2.16
   Compiling typenum v1.18.0
   Compiling aho-corasick v1.1.3
   Compiling rustix v1.0.1
   Compiling version_check v0.9.5
   Compiling generic-array v0.14.7
   Compiling num-traits v0.2.19
   Compiling byteorder v1.5.0
   Compiling regex-automata v0.4.9
   Compiling quote v1.0.40
   Compiling syn v2.0.99
   Compiling siphasher v1.0.1
   Compiling rand_core v0.6.4
   Compiling rand v0.8.5
   Compiling phf_shared v0.11.3
   Compiling errno v0.3.10
   Compiling getrandom v0.2.15
   Compiling phf_generator v0.11.3
   Compiling regex v1.11.1
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling phf_codegen v0.11.3
   Compiling utf8parse v0.2.2
   Compiling anstyle-parse v0.2.6
   Compiling digest v0.10.7
   Compiling is_terminal_polyfill v1.70.1
   Compiling anstyle-query v1.1.2
   Compiling colorchoice v1.0.3
   Compiling anstyle v1.0.10
   Compiling parse-zoneinfo v0.3.1
   Compiling num-integer v0.1.46
   Compiling cpufeatures v0.2.17
   Compiling clap_lex v0.7.4
   Compiling anstream v0.6.18
   Compiling unicode-width v0.2.0
   Compiling strsim v0.11.1
   Compiling cfg_aliases v0.2.1
   Compiling terminal_size v0.4.2
   Compiling core-foundation-sys v0.8.7
   Compiling nix v0.29.0
   Compiling clap_builder v4.5.35
   Compiling chrono-tz-build v0.4.0
   Compiling iana-time-zone v0.1.63
   Compiling either v1.15.0
   Compiling thiserror v2.0.12
   Compiling libm v0.2.11
   Compiling chrono v0.4.40
   Compiling chrono-tz v0.10.3
   Compiling blake3 v1.8.1
   Compiling bigdecimal v0.4.8
   Compiling powerfmt v0.2.0
   Compiling data-encoding v2.8.0
   Compiling time-core v0.1.4
   Compiling same-file v1.0.6
   Compiling arrayref v0.3.9
   Compiling num-conv v0.1.0
   Compiling constant_time_eq v0.3.1
   Compiling arrayvec v0.7.6
   Compiling walkdir v2.5.0
   Compiling time-macros v0.2.22
   Compiling deranged v0.4.0
   Compiling zerocopy-derive v0.7.35
   Compiling clap v4.5.35
   Compiling thiserror-impl v2.0.12
   Compiling data-encoding-macro-internal v0.1.15
   Compiling phf v0.11.3
   Compiling keccak v0.1.5
   Compiling socket2 v0.5.8
   Compiling zerocopy v0.7.35
   Compiling num_threads v0.1.7
   Compiling itoa v1.0.15
   Compiling uuhelp_parser v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uuhelp_parser)
   Compiling number_prefix v0.4.0
   Compiling uucore_procs v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uucore_procs)
   Compiling data-encoding-macro v0.1.17
   Compiling ppv-lite86 v0.2.20
   Compiling time v0.3.41
   Compiling rand_chacha v0.3.1
   Compiling dns-lookup v2.0.4
   Compiling sha3 v0.10.8
   Compiling blake2b_simd v1.0.3
   Compiling itertools v0.14.0
   Compiling os_display v0.1.4
   Compiling xattr v1.5.0
   Compiling num-bigint v0.4.6
   Compiling sha1 v0.10.6
   Compiling sha2 v0.10.8
   Compiling md-5 v0.10.6
   Compiling sm3 v0.4.2
   Compiling crc32fast v1.4.2
   Compiling z85 v3.0.6
   Compiling hex v0.4.3
   Compiling dunce v1.0.5
   Compiling glob v0.3.2
   Compiling wild v2.2.1
   Compiling clang-sys v1.8.1
   Compiling once_cell v1.20.3
   Compiling prettyplease v0.2.30
   Compiling minimal-lexical v0.2.1
   Compiling getrandom v0.3.1
   Compiling nom v7.1.3
   Compiling libloading v0.8.6
   Compiling bindgen v0.71.1
   Compiling itertools v0.13.0
   Compiling uucore v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uucore)
   Compiling cexpr v0.6.0
   Compiling log v0.4.26
   Compiling lazy_static v1.5.0
   Compiling rustc-hash v2.1.1
   Compiling cpp_common v0.5.10
   Compiling crunchy v0.2.3
   Compiling lock_api v0.4.12
   Compiling parking_lot_core v0.9.10
   Compiling zerocopy v0.8.23
   Compiling tiny-keccak v2.0.2
   Compiling smallvec v1.15.0
   Compiling rand_core v0.9.3
   Compiling scopeguard v1.2.0
   Compiling crossbeam-utils v0.8.21
   Compiling unicode-xid v0.2.6
   Compiling cpp_build v0.5.10
   Compiling rand_chacha v0.9.0
   Compiling bitflags v1.3.2
   Compiling cpp_macros v0.5.10
   Compiling mio v1.0.3
   Compiling const-random-macro v0.1.16
   Compiling uu_stdbuf_libstdbuf v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/stdbuf/src/libstdbuf)
   Compiling rand v0.9.0
   Compiling parking_lot v0.12.3
   Compiling filetime v0.2.25
   Compiling thiserror v1.0.69
   Compiling unicode-width v0.1.14
   Compiling pkg-config v0.3.32
   Compiling unicode-segmentation v1.12.0
   Compiling portable-atomic v1.11.0
   Compiling signal-hook v0.3.17
   Compiling radium v0.7.0
   Compiling convert_case v0.7.1
   Compiling onig_sys v69.8.1
   Compiling ansi-width v0.1.0
   Compiling crossbeam-epoch v0.9.18
   Compiling cpp v0.5.10
   Compiling const-random v0.1.18
   Compiling thiserror-impl v1.0.69
   Compiling nom v8.0.0
   Compiling hostname v0.4.0
   Compiling signal-hook-registry v1.4.2
   Compiling selinux-sys v0.6.14
   Compiling rayon-core v1.12.1
   Compiling tap v1.0.1
   Compiling foldhash v0.1.4
   Compiling equivalent v1.0.2
   Compiling nu-ansi-term v0.50.1
   Compiling fastrand v2.3.0
   Compiling allocator-api2 v0.2.21
   Compiling lscolors v0.20.0
   Compiling tempfile v3.19.1
   Compiling dlv-list v0.5.2
   Compiling hashbrown v0.15.2
   Compiling wyz v0.5.1
   Compiling fts-sys v0.2.16
   Compiling crossbeam-deque v0.8.6
   Compiling uutils_term_grid v0.6.0
   Compiling derive_more-impl v2.0.1
   Compiling kqueue-sys v1.0.4
   Compiling console v0.15.11
   Compiling fundu-core v0.3.1
   Compiling funty v2.0.0
   Compiling hashbrown v0.14.5
   Compiling litrs v0.4.1
   Compiling parse_datetime v0.8.0
   Compiling bitvec v1.0.1
   Compiling document-features v0.2.11
   Compiling ordered-multimap v0.7.3
   Compiling fundu v2.0.1
   Compiling indicatif v0.17.11
   Compiling derive_more v2.0.1
   Compiling uu_stdbuf v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/stdbuf)
   Compiling kqueue v1.0.8
   Compiling uu_ls v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/ls)
   Compiling lru v0.12.5
   Compiling signal-hook-mio v0.2.4
   Compiling filedescriptor v0.8.3
   Compiling selinux v0.5.1
   Compiling uu_base32 v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/base32)
   Compiling num-modular v0.5.1
   Compiling platform-info v2.0.5
   Compiling fsevent-sys v4.1.0
   Compiling notify-types v2.0.0
   Compiling trim-in-place v0.1.7
   Compiling quick-error v2.0.1
   Compiling compare v0.1.0
   Compiling notify v8.0.0
   Compiling rust-ini v0.21.1
   Compiling binary-heap-plus v0.5.0
   Compiling rayon v1.10.0
   Compiling crossterm v0.29.0
   Compiling num-prime v0.4.4
   Compiling bstr v1.11.3
   Compiling ctrlc v3.4.6
   Compiling coreutils v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils)
   Compiling memmap2 v0.9.5
   Compiling half v2.6.0
   Compiling gcd v2.3.0
   Compiling fs_extra v1.3.0
   Compiling roff v0.2.2
   Compiling bytecount v0.6.8
   Compiling unicode-linebreak v0.1.5
   Compiling smawk v0.3.2
   Compiling file_diff v1.0.0
   Compiling fnv v1.0.7
   Compiling self_cell v1.1.0
   Compiling linux-raw-sys v0.9.3
   Compiling uu_sort v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/sort)
   Compiling uu_install v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/install)
   Compiling textwrap v0.16.2
   Compiling uu_mv v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/mv)
   Compiling uu_more v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/more)
   Compiling uu_cp v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/cp)
   Compiling clap_mangen v0.2.26
   Compiling uu_wc v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/wc)
   Compiling uu_od v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/od)
   Compiling uu_dd v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/dd)
   Compiling uu_tac v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/tac)
   Compiling uu_factor v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/factor)
   Compiling uu_cut v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/cut)
   Compiling uu_env v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/env)
   Compiling uu_tail v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/tail)
   Compiling uu_chcon v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/chcon)
   Compiling uu_pr v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/pr)
   Compiling uu_uname v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/uname)
   Compiling uu_arch v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/arch)
   Compiling uu_basenc v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/basenc)
   Compiling uu_base64 v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/base64)
   Compiling uu_vdir v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/vdir)
   Compiling uu_dir v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/dir)
   Compiling uu_runcon v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/runcon)
   Compiling uu_sleep v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/sleep)
   Compiling uu_date v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/date)
   Compiling uu_touch v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/touch)
   Compiling uu_tr v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/tr)
   Compiling uu_mktemp v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/mktemp)
   Compiling uu_hostname v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/hostname)
   Compiling uu_shred v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/shred)
   Compiling uu_shuf v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/shuf)
   Compiling uu_csplit v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/csplit)
   Compiling uu_nl v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/nl)
   Compiling uu_cksum v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/cksum)
   Compiling uu_ptx v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/ptx)
   Compiling uu_hashsum v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/hashsum)
   Compiling uu_dircolors v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/dircolors)
   Compiling uu_chgrp v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/chgrp)
   Compiling uu_expand v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/expand)
   Compiling uu_nohup v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/nohup)
   Compiling uu_users v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/users)
   Compiling uu_printenv v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/printenv)
   Compiling uu_rmdir v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/rmdir)
   Compiling uu_chmod v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/chmod)
   Compiling uu_dirname v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/dirname)
   Compiling uu_head v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/head)
   Compiling uu_nproc v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/nproc)
   Compiling uu_pwd v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/pwd)
   Compiling uu_mkdir v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/mkdir)
   Compiling uu_split v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/split)
   Compiling uu_id v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/id)
   Compiling uu_du v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/du)
   Compiling uu_echo v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/echo)
   Compiling uu_ln v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/ln)
   Compiling uu_chown v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/chown)
   Compiling uu_nice v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/nice)
   Compiling uu_join v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/join)
   Compiling uu_true v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/true)
   Compiling uu_tsort v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/tsort)
   Compiling uu_tty v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/tty)
   Compiling onig v6.4.0
   Compiling uu_hostid v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/hostid)
   Compiling uu_numfmt v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/numfmt)
   Compiling uu_seq v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/seq)
   Compiling uu_printf v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/printf)
   Compiling uu_expr v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/expr)
   Compiling uu_readlink v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/readlink)
   Compiling uu_uniq v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/uniq)
   Compiling uu_truncate v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/truncate)
   Compiling uu_basename v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/basename)
   Compiling uu_chroot v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/chroot)
   Compiling uu_pathchk v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/pathchk)
   Compiling uu_stat v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/stat)
   Compiling uu_tee v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/tee)
   Compiling uu_groups v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/groups)
   Compiling uu_link v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/link)
   Compiling uu_timeout v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/timeout)
   Compiling uu_sync v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/sync)
   Compiling uu_unlink v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/unlink)
   Compiling uu_unexpand v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/unexpand)
   Compiling uu_paste v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/paste)
   Compiling uu_uptime v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/uptime)
   Compiling uu_pinky v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/pinky)
   Compiling uu_yes v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/yes)
   Compiling uu_sum v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/sum)
   Compiling uu_comm v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/comm)
   Compiling uu_fmt v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/fmt)
   Compiling uu_mkfifo v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/mkfifo)
   Compiling uu_realpath v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/realpath)
   Compiling uu_fold v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/fold)
   Compiling uu_test v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/test)
   Compiling uu_df v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/df)
   Compiling uu_cat v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/cat)
   Compiling uu_who v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/who)
   Compiling uu_kill v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/kill)
   Compiling uu_mknod v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/mknod)
   Compiling uu_rm v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/rm)
   Compiling uu_logname v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/logname)
   Compiling uu_whoami v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/whoami)
   Compiling uu_false v0.0.30 (/Users/kburke/src/github.com/uutils/coreutils/src/uu/false)
   Compiling clap_complete v4.5.47
error[E0425]: cannot find value `uumain` in crate `chcon`
   --> /Users/kburke/src/github.com/uutils/coreutils/target/release/build/coreutils-d16b8693e17bd9eb/out/uutils_map.rs:160:27
    |
160 |         ("chcon", (chcon::uumain, chcon::uu_app)),
    |                           ^^^^^^ not found in `chcon`
    |
help: consider importing one of these functions
   --> src/bin/coreutils.rs:8:1
    |
8   + use arch::uumain;
   --> |src/bin/coreutils.rs:8:1
    |
8   + use base32::uumain;
   --> |src/bin/coreutils.rs:8:1
    |
8   + use base64::uumain;
   --> |src/bin/coreutils.rs:8:1
    |
8   + use basename::uumain;
    |
      and 95 other candidates
help: if you import `uumain`, refer to it directly
    |
160 -         ("chcon", (chcon::uumain, chcon::uu_app)),
160 +         ("chcon", (uumain, chcon::uu_app)),
    |

error[E0425]: cannot find value `uu_app` in crate `chcon`
   --> /Users/kburke/src/github.com/uutils/coreutils/target/release/build/coreutils-d16b8693e17bd9eb/out/uutils_map.rs:160:42
    |
160 |         ("chcon", (chcon::uumain, chcon::uu_app)),
    |                                          ^^^^^^ not found in `chcon`
    |
help: consider importing one of these functions
   --> src/bin/coreutils.rs:8:1
    |
8   + use arch::uu_app;
   --> |src/bin/coreutils.rs:8:1
    |
8   + use base32::uu_app;
   --> |src/bin/coreutils.rs:8:1
    |
8   + use base64::uu_app;
   --> |src/bin/coreutils.rs:8:1
    |
8   + use basename::uu_app;
    |
      and 94 other candidates
help: if you import `uu_app`, refer to it directly
    |
160 -         ("chcon", (chcon::uumain, chcon::uu_app)),
160 +         ("chcon", (chcon::uumain, uu_app)),
    |

error[E0425]: cannot find value `uumain` in crate `runcon`
   --> /Users/kburke/src/github.com/uutils/coreutils/target/release/build/coreutils-d16b8693e17bd9eb/out/uutils_map.rs:237:29
    |
237 |         ("runcon", (runcon::uumain, runcon::uu_app)),
    |                             ^^^^^^ not found in `runcon`
    |
help: consider importing one of these functions
   --> src/bin/coreutils.rs:8:1
    |
8   + use arch::uumain;
   --> |src/bin/coreutils.rs:8:1
    |
8   + use base32::uumain;
   --> |src/bin/coreutils.rs:8:1
    |
8   + use base64::uumain;
   --> |src/bin/coreutils.rs:8:1
    |
8   + use basename::uumain;
    |
      and 95 other candidates
help: if you import `uumain`, refer to it directly
    |
237 -         ("runcon", (runcon::uumain, runcon::uu_app)),
237 +         ("runcon", (uumain, runcon::uu_app)),
    |

error[E0425]: cannot find value `uu_app` in crate `runcon`
   --> /Users/kburke/src/github.com/uutils/coreutils/target/release/build/coreutils-d16b8693e17bd9eb/out/uutils_map.rs:237:45
    |
237 |         ("runcon", (runcon::uumain, runcon::uu_app)),
    |                                             ^^^^^^ not found in `runcon`
    |
help: consider importing one of these functions
   --> src/bin/coreutils.rs:8:1
    |
8   + use arch::uu_app;
   --> |src/bin/coreutils.rs:8:1
    |
8   + use base32::uu_app;
   --> |src/bin/coreutils.rs:8:1
    |
8   + use base64::uu_app;
   --> |src/bin/coreutils.rs:8:1
    |
8   + use basename::uu_app;
    |
      and 94 other candidates
help: if you import `uu_app`, refer to it directly
    |
237 -         ("runcon", (runcon::uumain, runcon::uu_app)),
237 +         ("runcon", (runcon::uumain, uu_app)),
    |

For more information about this error, try `rustc --explain E0425`.
error: could not compile `coreutils` (bin "coreutils") due to 4 previous errors
make: *** [build-coreutils] Error 101
```

This ticket - https://github.com/uutils/coreutils/issues/7490 - mentioned that runcon was "missing" but that doesn't seem to be the issue here, it seems like it's some kind of version incompatibility issue.

**Comment by kevinburke** [comment]
I can't reproduce this error on 0.0.30

**Comment by kevinburke** [comment]
Bisected to commit https://github.com/uutils/coreutils/commit/2555fd4039c6d0f0148398d66b5e2acd99832a5b. Before this, there were a number of different compilation errors - that's the first commit that starts showing the error displayed above.

**Comment by drinkcat** [comment]
`chcon` and `runcon` should not be built on Mac (those are Linux/SELinux specific). Not sure how the `make install` thing works, but it does appear it doesn't set the correct set of features?

**Comment by kevinburke** [comment]
>  it does appear it doesn't set the correct set of features?

I would guess so yes. If you want to give me some advice on how I can tell you which set of features it's picking I'd be happy to.
