### ISSUE TITLE
0.6.0 release broken on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [uutils/coreutils#11175]
Hi,

`coreutils` v0.5.0 builds fine on NetBSD, while v0.6.0 fails to build `uucore` with:

```
error[E0609]: no field `st_atime_nsec` on type `FileStat`
   --> /usr/pkgsrc/wip/nushell/work/vendor/uucore-0.6.0/src/lib/features/safe_traversal.rs:482:23
    |
482 |             self.stat.st_atime_nsec
    |                       ^^^^^^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
482 -             self.stat.st_atime_nsec
482 +             self.stat.st_atimensec
    |

error[E0609]: no field `st_mtime_nsec` on type `FileStat`
   --> /usr/pkgsrc/wip/nushell/work/vendor/uucore-0.6.0/src/lib/features/safe_traversal.rs:504:23
    |
504 |             self.stat.st_mtime_nsec
    |                       ^^^^^^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
504 -             self.stat.st_mtime_nsec
504 +             self.stat.st_mtimensec
    |

error[E0609]: no field `st_ctime_nsec` on type `FileStat`
   --> /usr/pkgsrc/wip/nushell/work/vendor/uucore-0.6.0/src/lib/features/safe_traversal.rs:526:23
    |
526 |             self.stat.st_ctime_nsec
    |                       ^^^^^^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
526 -             self.stat.st_ctime_nsec
526 +             self.stat.st_ctimensec
    |
```

This was observed while building `nushell` v0.111.0 see, https://github.com/nushell/nushell/issues/17695#issuecomment-3984104778

The same happens building `coreutils` standalone with cargo.

The reason is rather obvious,
```
~> grep -r "st_atime_nsec" libc-0.2.178/src/unix/bsd/netbsdlike/netbsd
Exception: grep exited with 1
~> grep -r "st_mtime_nsec" libc-0.2.178/src/unix/bsd/netbsdlike/netbsd
Exception: grep exited with 1
~> grep -r "st_ctime_nsec" libc-0.2.178/src/unix/bsd/netbsdlike/netbsd
Exception: grep exited with 1
~> grep -r "st_atimensec" libc-0.2.178//src/unix/bsd/netbsdlike/netbsd
libc-0.2.178/src/unix/bsd/netbsdlike/netbsd/mod.rs:        pub st_atimensec: c_long,
~> grep -r "st_mtimensec" libc-0.2.178//src/unix/bsd/netbsdlike/netbsd
libc-0.2.178/src/unix/bsd/netbsdlike/netbsd/mod.rs:        pub st_mtimensec: c_long,
~> grep -r "st_ctimensec" libc-0.2.178//src/unix/bsd/netbsdlike/netbsd
libc-0.2.178/src/unix/bsd/netbsdlike/netbsd/mod.rs:        pub st_ctimensec: c_long,
```

And the same output is valid for the latest `libc`, v0.2.182.

Any reason for this regression and are you willing to fix it?

**Comment by cakebaker** [comment]
We currently don't run NetBSD in the CI and thus we don't notice regressions on NetBSD :|  Did you try it with `main`?

**Comment by 0323pin** [comment]
> We currently don't run NetBSD in the CI and thus we don't notice regressions on NetBSD :|

That makes sense.

How would you like to fix this?
Should those be gated with an exception for NetBSD and `target_os = netbsd` handled separatly?

**Comment by cakebaker** [comment]
Yes, that sounds reasonable.

**Comment by 0323pin** [comment]
> Did you try it with main?

```
~> git clone https://github.com/uutils/coreutils
~> cd coreutils
~> cargo build
[...]
error[E0609]: no field `st_atime_nsec` on type `FileStat`
   --> src/uucore/src/lib/features/safe_traversal.rs:713:23
    |
713 |             self.stat.st_atime_nsec
    |                       ^^^^^^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
713 -             self.stat.st_atime_nsec
713 +             self.stat.st_atimensec
    |

error[E0609]: no field `st_mtime_nsec` on type `FileStat`
   --> src/uucore/src/lib/features/safe_traversal.rs:735:23
    |
735 |             self.stat.st_mtime_nsec
    |                       ^^^^^^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
735 -             self.stat.st_mtime_nsec
735 +             self.stat.st_mtimensec
    |

error[E0609]: no field `st_ctime_nsec` on type `FileStat`
   --> src/uucore/src/lib/features/safe_traversal.rs:757:23
    |
757 |             self.stat.st_ctime_nsec
    |                       ^^^^^^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
757 -             self.stat.st_ctime_nsec
757 +             self.stat.st_ctimensec
    |
[...]
```

**Comment by 0323pin** [comment]
> Yes, that sounds reasonable.

Should the code apply to all OSs except NetBSD?

**Comment by cakebaker** [comment]
> Should the code apply to all OSs except NetBSD?

Yes.

**Comment by oech3** [comment]
cargo deny complain if we mixed different version of `libc`s for each platforms. On the other hand, downgrading for all platforms might regress some bugs which is impossible to detect at CI (e.g. glibc 2.42+ specific bug).

**Comment by 0323pin** [comment]
The following patch fixes the build, do you want a PR for it?

```
--- safe_traversal.rs	2026-03-02 15:10:42.988719559 +0100
+++ Downloads/coreutils/src/uucore/src/lib/features/safe_traversal.rs	2026-03-02 15:19:35.142467595 +0100
@@ -22,10 +22,10 @@
 use std::path::{Path, PathBuf};
 
 use nix::dir::Dir;
-use nix::fcntl::{OFlag, openat};
+use nix::fcntl::{openat, OFlag};
 use nix::libc;
-use nix::sys::stat::{FchmodatFlags, FileStat, Mode, fchmodat, fstatat, mkdirat};
-use nix::unistd::{Gid, Uid, UnlinkatFlags, fchown, fchownat, unlinkat};
+use nix::sys::stat::{fchmodat, fstatat, mkdirat, FchmodatFlags, FileStat, Mode};
+use nix::unistd::{fchown, fchownat, unlinkat, Gid, Uid, UnlinkatFlags};
 use os_display::Quotable;
 
 use crate::translate;
@@ -53,7 +53,11 @@
 
 impl From<bool> for SymlinkBehavior {
     fn from(follow: bool) -> Self {
-        if follow { Self::Follow } else { Self::NoFollow }
+        if follow {
+            Self::Follow
+        } else {
+            Self::NoFollow
+        }
     }
 }
 
@@ -704,13 +708,21 @@
     }
 
     fn atime_nsec(&self) -> i64 {
-        #[cfg(target_pointer_width = "32")]
+        #[cfg(target_os = "netbsd")]
         {
-            self.stat.st_atime_nsec.into()
+            self.stat.st_atimensec as i64
         }
-        #[cfg(not(target_pointer_width = "32"))]
+
+        #[cfg(not(target_os = "netbsd"))]
         {
-            self.stat.st_atime_nsec
+            #[cfg(target_pointer_width = "32")]
+            {
+                self.stat.st_atime_nsec.into()
+            }
+            #[cfg(not(target_pointer_width = "32"))]
+            {
+                self.stat.st_atime_nsec
+            }
         }
     }
 
@@ -726,13 +738,21 @@
     }
 
     fn mtime_nsec(&self) -> i64 {
-        #[cfg(target_pointer_width = "32")]
+        #[cfg(target_os = "netbsd")]
         {
-            self.stat.st_mtime_nsec.into()
+            self.stat.st_mtimensec as i64
         }
-        #[cfg(not(target_pointer_width = "32"))]
+
+        #[cfg(not(target_os = "netbsd"))]
         {
-            self.stat.st_mtime_nsec
+            #[cfg(target_pointer_width = "32")]
+            {
+                self.stat.st_mtime_nsec.into()
+            }
+            #[cfg(not(target_pointer_width = "32"))]
+            {
+                self.stat.st_mtime_nsec
+            }
         }
     }
 
@@ -748,13 +768,21 @@
     }
 
     fn ctime_nsec(&self) -> i64 {
-        #[cfg(target_pointer_width = "32")]
+        #[cfg(target_os = "netbsd")]
         {
-            self.stat.st_ctime_nsec.into()
+            self.stat.st_ctimensec as i64
         }
-        #[cfg(not(target_pointer_width = "32"))]
+
+        #[cfg(not(target_os = "netbsd"))]
         {
-            self.stat.st_ctime_nsec
+            #[cfg(target_pointer_width = "32")]
+            {
+                self.stat.st_ctime_nsec.into()
+            }
+            #[cfg(not(target_pointer_width = "32"))]
+            {
+                self.stat.st_ctime_nsec
+            }
         }
     }
 
```

**Comment by cakebaker** [comment]
Yes, please :)

**Comment by 0323pin** [comment]
> Yes, please :)

Coming soon.

**Comment by oech3** [comment]
>We currently don't run NetBSD in the CI

@lcheylus Can we add `cargo check` only CI for NetBSD which is faster than `cargo test`?

**Comment by 0323pin** [comment]
Two test failed. What Rust version are you using in the CI? I've used `rustfmt` from 1.93.1

**Comment by cakebaker** [comment]
We currently use Rust 1.93.1.

**Comment by 0323pin** [comment]
> We currently use Rust 1.93.1.

Do you know why those tests are failing?

**Comment by cakebaker** [comment]
I think you have to provide `--edition=2024` when running `rustfmt` (or use `cargo fmt`). And to make the "spelling" job pass you can add the words to the `spell-checker:ignore` setting at the top of the file.

The other failing jobs you can ignore as they are unrelated to your PR.

**Comment by oech3** [comment]
@cakebaker The failing job is probably fixed by https://github.com/uutils/coreutils/pull/11169

**Comment by 0323pin** [comment]
Only one [failure](https://github.com/uutils/coreutils/actions/runs/22582429126/job/65417952211?pr=11176) now.

What to do?

**Comment by cakebaker** [comment]
> What to do?

You can add the unknown words to the `spell-checker:ignore` setting at the top of the file.

**Comment by 0323pin** [comment]
@cakebaker Cheers! I'll push that either tonight or tomorrow.

**Comment by 0323pin** [comment]
Just managed to push this before dinner :)

**Comment by 0323pin** [comment]
I would say it's green now. [This](https://github.com/uutils/coreutils/actions/runs/22586755232/job/65434898120?pr=11176) has nothing to do with my changes.
