### PR TITLE
Add "nix" to Cargo.toml to fix compile error

### PR DESCRIPTION
**Pull request by cakebaker**
https://github.com/uutils/coreutils/commit/48a521224edb29b3c1779142d1953f658de0762f introduced a compile error when running the df tests:
```
$ cargo test --features "df" --no-default-features
   Compiling uucore v0.0.13 (/home/dho/projects/coreutils/src/uucore)
error[E0433]: failed to resolve: use of undeclared crate or module `nix`
   --> src/uucore/src/lib/features/fsext.rs:670:48
    |
670 |             unsafe { &*(&self.f_fsid as *const nix::sys::statfs::fsid_t as *const [u32; 2]) };
    |                                                ^^^ use of undeclared crate or module `nix`

```
However, when running `cargo run df`, there is no compilation error. I don't know why this works fine, I expected the same compilation error as above. So I'm not sure whether this PR is the correct fix.

### CODE REVIEW

**Review by jfinkels — APPROVED** [review]

**Comment by jtracey** [comment]
Sorry about that, slipped through as it only happens when compiled on its own (you can also trigger it with `cargo build -p uu_df`). I ran some tests on my machine, and it looks like `df` is the only util with this problem. But yes, your patch looks right to me.

Script to test everything (we may want to add this or similar to the CI):
```sh
for util in $(ls src/uu/); do
  echo "building $util"
  cargo build -p uu_$util
done
```
